### ISSUE TITLE
Вопрос по кан шине

### ISSUE THREAD

**Issue by gehreleth** [autowp/autowp#103]
Мы тут пишем систему помощи дла парковки, меня интересует у какой модели есть пульсы для всех четырех колес и угол поворота руля на кан шине. Оригинальной машины заказчик пока не завез, хотим пока арендовать что-то похожее

**Comment by autowp** [comment]
Не знаю. Вот у машин PSA такое есть: http://autowp.github.io/ (см. 0E6, 30D и руль в 10B вроде)
