### ISSUE TITLE
Possible bug re date added

### ISSUE THREAD

**Issue by terrorist96** [autowp/autowp#106]
Example: [This](https://en.wheelsage.org/audi/e-tron/prototype/pictures/v9r2jv/) says it was uploaded on April 20, 2018. But I cannot find that picture [here](https://en.wheelsage.org/ng/new/2018-04-20). Why?

**Comment by autowp** [comment]
Upload & moderation accept dates

**Comment by terrorist96** [comment]
So on the `New pictures` page, which date should it appear?

**Comment by autowp** [comment]
nowhere

**Comment by terrorist96** [comment]
So this is intended behavior? Because almost every image I've seen, the `Added by` date matches the date in the `New pictures` page.

**Comment by autowp** [comment]
I think yes. Part of pictures uploaded & approved in the same day

**Comment by terrorist96** [comment]
Okay thanks.

**Comment by terrorist96** [comment]
@autowp also some don't have a date at all:
https://en.wheelsage.org/pagani/zonda/cinque/pagani_zonda_cinque/pictures/286443/
