### ISSUE TITLE
Добавить кнопку "добавить ещё фото" на страницы фотографий с 2-3-мя разными моделями вместе

### ISSUE THREAD

**Issue by Wheeler2017** [autowp/autowp#87]
пример: https://www.autowp.ru/john-deere/john_r-series_tractors/112721/ жму на фото https://www.autowp.ru/john-deere/john_r-series_tractors/112721/118270/pictures/cjq4ej/ привязанное к модели John Deere 8370R '2013–н.в. есть только вариант "Предложить замену картинке", но мне нужен вариант "добавить еще фото  John Deere 8370R '2013"
я же нажал на фото, привязанное к конкретной модели. получается, сайт этого не понимает. для меня крайне неудобно поднимать глаза в правый верхний угол сайта, нажимать "еще", "добавить картинку", "добавить изображение" и т.д., т.к. я нередко сталкиваюсь с этим.

**Comment by autowp** [comment]
Done
https://github.com/autowp/autowp/commit/aa75c130b6380dff3f942dcf61dac83338bc94e8
