### ISSUE TITLE
Перевод сайта на Украинский язык.

### ISSUE THREAD

**Issue by Malyucov** [autowp/autowp#95]
Доброго времени суток. 
Помогаю развитию сайта. Положил файл с переводом на украинский. 
Если нужно дополнительная помощь, пишите.

**Comment by autowp** [comment]
Здравсвуйте. Куда положили, я что-то не вижу?

**Comment by autowp** [comment]
@Malyucov я выгрузил тексты на Oneskyapp, если есть желание добавить язык: переведите там и по готовности я добавлю переключатель на сайте: https://osqbfbz.oneskyapp.com/collaboration/project?id=129670

**Comment by AcidJumper** [comment]
Буду также переводить.
Но есть вопросы (перевожу с рус. на укр.), как переводить следующее:
Двигатель %s
%BRAND_NAME% %DPBRAND_NAME% 
Самые %MOST_NAME% %BRAND_NAME%
и такое
{count, plural, one {{count} изображение} few {{count} изображения} many {{count} изображений} other {{count} изображений}}
?

**Comment by AcidJumper** [comment]
@Malyucov и @autowp разберитесь можно ли выложить уже готовый файл перевода) Хочу знать, стоит ли браться за перевод по ссылке выше.

**Comment by autowp** [comment]
@AcidJumper 

Файлов выкладывать не надо. Переводите на oneskyapp.

Конструкции вида `%BRAND_NAME%`, `%1$s`, `{count}` и подобное переводить не надо - оставлять как есть. Это placeholder, т.е. конструкция, которая будет заменена на какое-то значение (число сообщений или название марки)

`{count, plural, one {{count} изображение} few {{count} изображения} many {{count} изображений} other {{count} изображений}}` - это работа с числительными. 

1 изображение
2 изображения
5 изображений

Украинский и русский язык работают в этом аспекте одинаково. 
Переводить здесь надо только то, что написано по-русски. Конструкции `{count}`, `plural`, `one`, `few`, `many`, `other` должы остаться без изменений.

Если интересны подробности - называется это messageformat и описано здесь: 
http://userguide.icu-project.org/formatparse/messages
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

**Comment by AcidJumper** [comment]
@autowp Спасибо, понял.

**Comment by Huracan911** [comment]
Перевод на треть готов. Продолжаю работать.

**Comment by autowp** [comment]
@Huracan911 Отлично

**Comment by Huracan911** [comment]
Готово

**Comment by autowp** [comment]
@Huracan911 Выгрузил на сайт https://uk.wheelsage.org/

Спасибо!

Если будет возможность, время от времени поглядывайте - возможно будут появляться новые тексты для перевода или замечания по имеющимся
